# Use the official Microsoft SQL Server 2022 image as a base
FROM mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04

# Set environment variables
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=StrongP@ssw0rd123
ENV MSSQL_PID=Evaluation

# Copy the seed data SQL script to the container
COPY init-db.sql /usr/src/app/init-db.sql

# Run the SQL Server process and seed the database
CMD /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -i /usr/src/app/init-db.sql & wait"
